#!/bin/bash

if [[ $1 == "up" ]]; then
	rclone copy -LuP /home/adam/drive drive:
fi

if [[ $1 == "down" ]]; then
	rclone copy drive: /home/adam/drive -P --exclude SVČ*/ --drive-chunk-size 128M
fi

if [[ $1 == "	q
