#!/bin/bash

while IFS=, read -r line; do
	program=($line)
	if [ -z "${program[1]}" ]; then 
		echo "(xbps) Installing $program"
		xbps-install -Sy $program &>/dev/null
	elif [ -n "${program[1]}" ]; then
		cd /home/$USER/builds
		echo "(git) Installing ${program[0]} from ${program[1]}"
		sudo -u $USER git clone ${program[1]}
		cd ${program[0]}
		sudo make clean install
	fi
done < /home/$USER/.scripts/install/programs;
