#!/bin/bash

choice=$(echo -e "Suspend\nShutdown\nReboot" | dmenu -i) 
if [[ "$choice" == "Suspend" ]]; then
	systemctl suspend
elif [[ "$choice" == "Shutdown" ]]; then
	sudo shutdown now
elif [[ "$choice" == "Reboot" ]]; then
	sudo reboot now
fi
