#!/usr/bin/env bash

function show_brightness_notification() {
	br=$(light -G)
	brightness=$(printf "%.*f" 0 $br)
	bar=$(echo "$(seq -s "─" $(($brightness/5)))$(seq -s " " $(((100-$brightness)/5)))" | sed 's/[0-9]//g')
	dunstify -t 2000 -r 556 "☀$(printf "%3.2f%" $br)% | $bar |"
}

case $1 in
	up)
		light -A $(light -G)
		show_brightness_notification
	;;
	down)
		light -U $(echo "$(light -G)/2" | $(which bc) -l)
		show_brightness_notification
	;;
esac
