#!/bin/bash
# A script for automatic compiling of stuff from vim

case "$1" in
	*tex) latexmk --shell-escape -pdf $1 || read ;;
	*md) pandoc -o "$(basename $1 .md).pdf" $1 ;;
	*asy) asy $1 || read -n 1 -s -r -p "Press any key to continue" ;;
	*c) gcc $1 -lm -o $(echo $1 | sed 's/..$//') ;;
	*) ./$1
esac

