#!/bin/bash
# Script for mounting usb devices using dmenu

list=$(lsblk --list -p -n -o NAME,TYPE,MOUNTPOINT | awk '$2=="part"&&!/sda/{print $1 " " $3}' | tac)

if [[ -z $list ]]; then
	notify-send "Nothing to mount."
	exit
fi

device=$(echo $list | sed 's/\s/\n/g' | dmenu)

if [ -z "$(mount | grep usb1)"]; then
	mnt="$mnt/home/mnt/usb1"
fi
if [ -z "$(mount | grep usb2)"]; then
	mnt="$mnt\n/home/mnt/usb2"
fi
if [ -z "$(mount | grep usb3)"]; then
	mnt="$mnt\n/home/mnt/usb3"
fi
mnt=$(echo -e $mnt | dmenu)

if [[ -n $device ]] && [[ -n $mnt ]]; then 
	notify-send "Mounting $device to $mnt" 
	sudo -u $USER mount $device $mnt
else
	notify-send "Not mounting anything."
fi
