#!/bin/bash
# By Adam Krivka (aidam38)

cd ~

if [[ ! -d .git/ ]]; then
	echo "Initializing git directory."
	git init
fi

if [[ ! "$(git remote)" =~ "origin" ]]; then
	git remote add origin https://github.com/aidam38/adamos
fi

git add .
git commit -v
git push origin master
