#!/bin/bash

brightness=$(light -G)
battery=$(sudo tlp-stat -b | grep "Charge total" | awk '{print $5}')
if [ "$(pamixer --get-mute)" = "true" ]; then
	vol="-1"
else 
	vol="$(pamixer --get-volume)"
fi

xsetroot -name "☀$(printf "%.*f\n" 0 $brightness)% | ⚡$battery% | 🔊$vol% | $(date "+%a %d. %m. | %T")"
