#!/bin/bash
# Script for mounting usb devices using dmenu

list=$(lsblk --list -p -n -o NAME,TYPE,MOUNTPOINT | awk '$2=="part"&&!/sda/{print $1 " " $3}' | tac)
echo $list

device=$(echo -e $list | dmenu)
mntpos=""
if [ -z "$(mount | grep usb1)"]; then
	mnt="$mnt/home/mnt/usb1"
fi
if [ -z "$(mount | grep usb2)"]; then
	mnt="$mnt\n/home/mnt/usb2"
fi
if [ -z "$(mount | grep usb3)"]; then
	mnt="$mnt\n/home/mnt/usb3"
fi
mnt=$(echo -e $mnt | dmenu)

notify-send "Mounting $device to $mnt"
sudo -u $USER mount $device $mnt

