#!/bin/bash
# Script for unmounting usb devices using dmenu

list=$(lsblk --list -p -n -o NAME,TYPE,MOUNTPOINT | awk '$2=="part"&&!/sda/{print $1 " " $3}' | tac)

device=$(echo -e $list | dmenu)

if [[ -n $device ]]; then 
	notify-send "Unmounting $device" 
	sudo -u $USER umount $device
else
	notify-send "Not unmounting anything."
fi

