#!/bin/sh

mimetype=$(file --mime-type -Lb "$1")
extension=$(echo "${1##*.}" | awk '{print tolower($0)}')
notify-send "$mimetype a $extension"

case "$1" in
    *.tar*) tar -xz "$1";;
    *.zip) unzip "$1";;
    *.rar) unrar "$1";;
    *.7z) 7z "$1";;
    *.pdf) st -e zathura "$1" &;;
    *.jpg|.png) rifle_sxiv.sh "$1";;
    *) vim "$1";;
esac
