#!/bin/bash

# This script records a screencast with audio and video.

filename="$HOME/screencast.mkv"

# For Pulseaudio with ALSA:
record_pulse() { \
ffmpeg -y \
-f x11grab \
-framerate 60 \
-s $(xdpyinfo | grep dimensions | awk '{print $2;}') \
-i :0.0 \
-f alsa -i default \
-r 30 \
 -c:v libx264rgb -crf 0 -preset ultrafast -c:a flac $filename ;}

record_pulse
